variable "hcloud_token" {
  type      = string
  default   = "${env("HCLOUD_TOKEN")}"
  sensitive = true
}

variable "hcloud_ssh_key" {
  type      = string
  default   = "${env("HCLOUD_SSH_KEY")}"
  sensitive = true
}

variable "k8s_version" {
  type    = string
  default = "1.26.3"
}

variable "container_runtime" {
  type    = string
  default = "containerd"
}

variable "base_image" {
  type    = string
  default = "fedora-37"
}

variable "location" {
    type = string
    default = "ash"
}

variable "server_type" {
    type = string
    default = "cpx11"
}

locals {
    image_name = "packer-${var.base_image}-${var.k8s_version}-${var.container_runtime}-{{isotime `2006-01-02T150405Z`}}"
}

source "hcloud" "autogenerated_1" {
  image       = "${var.base_image}"
  location    = "${var.location}"
  server_type = "${var.server_type}"
  snapshot_labels = {
    caph-image-name = "${local.image_name}"
    k8s-version = "${var.k8s_version}"
    base-image = "${var.base_image}"
    container-runtime = "${var.container_runtime}"
  }
  snapshot_name = "${local.image_name}"
  ssh_username  = "root"
  ssh_keys = ["${var.hcloud_ssh_key}"]
  token         = "${var.hcloud_token}"
  # Not sure if/why this would be necessary? https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2
  #user_data     = "#cloud-config\n runcmd:\n - update-crypto-policies --set LEGACY"
}

build {
  sources = ["source.hcloud.autogenerated_1"]
  provisioner "ansible" {
        user = "root"
        use_proxy = false
        playbook_file = "./ansible/playbook.yaml"
        extra_arguments = ["--extra-vars=kubernetes_version=${var.k8s_version}"]
        #extra_arguments = ["-vv"]
  }
}
