---
- name: Ensure inotify-tools installed
  ansible.builtin.dnf:
    name:
    - inotify-tools

- name: Ensure fix-advertise-address.sh exists
  ansible.builtin.copy:
    dest: /usr/local/bin/fix-advertise-address.sh
    mode: '0755'
    content: |
      #!/bin/bash

      CONF_FILES="/etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf"
      MANIFEST_FOLDER=/etc/kubernetes/manifests
      while true ; do
          inotifywait --recursive --event modify --event create ${MANIFEST_FOLDER} ${CONF_FILES}
          INTERNAL_IP=$(ip -4 addr show dev enp7s0 | egrep -m1 -o "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}" | head -n 1)
          EXTERNAL_IP=$(ip -4 addr show dev eth0 | egrep -m1 -o "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}" | head -n 1)
          for manifest in $(ls ${MANIFEST_FOLDER}/* ${CONF_FILES}) ; do
              sed -i -e "s/${EXTERNAL_IP}/${INTERNAL_IP}/g" ${manifest}
              #sed -i -e "s/${EXTERNAL_IP}/${INTERNAL_IP}/g" -e "s/0\.0\.0\.0/${INTERNAL_IP}/g" -e "s/127\.0\.0\.1/${INTERNAL_IP}/g" ${manifest}
          done
      done

- name: Ensure fix-advertise-address.sh service exists
  ansible.builtin.copy:
    dest: /etc/systemd/system/fix-advertise-address.service
    content: |
      [Unit]
      Description=Script to fix kube-apiserver advertise-address
      Before=kubelet.service
      Wants=network-online.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/fix-advertise-address.sh
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure
      RestartSec=42s

      [Install]
      WantedBy=multi-user.target

- name: Ensure fix-advertise-address.sh service enabled
  ansible.builtin.systemd:
    name: fix-advertise-address.service
    daemon_reload: true
    state: stopped
    enabled: true
